# Generated by Django 4.0.6 on 2022-07-21 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About_me',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='firstname (e.g. Abdullah)', max_length=20)),
                ('age', models.DateField(help_text='your age (e.g. 30)')),
                ('programming_language', models.CharField(help_text='programming language (e.g. python)', max_length=15)),
            ],
        ),
    ]
