# Generated by Django 4.0.6 on 2022-07-21 16:22

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('about_me', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about_me',
            name='name',
        ),
        migrations.AddField(
            model_name='about_me',
            name='firstname',
            field=models.CharField(default=datetime.datetime(2022, 7, 21, 16, 22, 3, 621708, tzinfo=utc), help_text='Firstname (e.g. Abdullah)', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about_me',
            name='lastname',
            field=models.CharField(default=django.utils.timezone.now, help_text='Lastname (e.g. Salaam)', max_length=255),
            preserve_default=False,
        ),
    ]
