# Generated by Django 4.0.6 on 2022-07-21 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_me', '0002_remove_about_me_name_about_me_firstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_me',
            name='firstname',
            field=models.CharField(help_text='Firstname (e.g. Abdullah)', max_length=20),
        ),
        migrations.AlterField(
            model_name='about_me',
            name='lastname',
            field=models.CharField(help_text='Lastname (e.g. Salaam)', max_length=20),
        ),
    ]
